### ISSUE TITLE
EsReader job.json中的 table字段如何定义？能给一下具体es实际数据案例说明吗？

### ISSUE THREAD

**Issue by YuanYuanDeLiShu** [Kestrong/datax-elasticsearch#3]
`            "table":{
              "name": "TACHE",
              "filter": "pk != null",
              "nameCase": "UPPERCASE",
              "column": [
                {
                  "name": "flow_id",
                  "alias": "pk", 
                },
                {
                  "name": "taches",
                  "child": [
                    {
                      "name": "tch_id"
                    },
                    {
                      "name": "tch_mod"
                    },
                    {
                      "name": "flow_id"
                    }
                  ]
                }
              ]
            }`

**Comment by Kestrong** [comment]
> ` "table":{ "name": "TACHE", "filter": "pk != null", "nameCase": "UPPERCASE", "column": [ { "name": "flow_id", "alias": "pk", }, { "name": "taches", "child": [ { "name": "tch_id" }, { "name": "tch_mod" }, { "name": "flow_id" } ] } ] }`

查看[elasticsearchreader.md](https://github.com/Kestrong/datax-elasticsearch/blob/master/elasticsearchreader/doc/elasticsearchreader.md)
