### ISSUE TITLE
无法打包

### ISSUE THREAD

**Issue by eriendeng** [Kestrong/datax-elasticsearch#6]
无法打包，缺datax-common找不到，请问有release吗

**Comment by Kestrong** [comment]
> 无法打包，缺datax-common找不到，请问有release吗

插件要在阿里的datax框架下运行的，先下载datax源码编译 install到本地仓库。

**Comment by Apophisdeity** [comment]
你好,在我将datax-common install在本地以后,使用mvn -U clean package assembly:assembly -Dmaven.test.skip=true 编译elasticsearchreader,但是会提示"找不到符号"错误(EsReader.java,364行),排查发现Column本身没有setName方法

**Comment by mushanzi1216** [comment]
> 你好,在我将datax-common install在本地以后,使用mvn -U clean package assembly:assembly -Dmaven.test.skip=true 编译elasticsearchreader,但是会提示"找不到符号"错误(EsReader.java,364行),排查发现Column本身没有setName方法

同样问题 请问你解决了嘛

**Comment by Kestrong** [comment]
> > 你好,在我将datax-common install在本地以后,使用mvn -U clean package assembly:assembly -Dmaven.test.skip=true 编译elasticsearchreader,但是会提示"找不到符号"错误(EsReader.java,364行),排查发现Column本身没有setName方法
> 
> 同样问题 请问你解决了嘛

@mushanzi1216 @Apophisdeity 拉取下最新的代码，已经修复了。

**Comment by mushanzi1216** [comment]
> > > 你好,在我将datax-common install在本地以后,使用mvn -U clean package assembly:assembly -Dmaven.test.skip=true 编译elasticsearchreader,但是会提示"找不到符号"错误(EsReader.java,364行),排查发现Column本身没有setName方法
> > 
> > 
> > 同样问题 请问你解决了嘛
> 
> @mushanzi1216 @Apophisdeity 拉取下最新的代码，已经修复了。

感谢 已经可以了
